name: Test
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run setup.sh
        run: |
          cd ~
          pwd
